# Generated by Django 3.0.8 on 2020-07-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bowl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('style', models.CharField(choices=[('Tonkotsu', 'Tonkotsu'), ('Miso', 'Miso'), ('Shoyu', 'Shoyu'), ('Shio', 'Shio'), ('Other', 'Other')], max_length=20)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
    ]
