# Generated by Django 3.0.8 on 2020-07-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowl',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
