# Generated by Django 3.0.8 on 2020-07-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0002_bowl_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bowl',
            name='created_at',
        ),
    ]
